#!/usr/bin/env bash
if [ ! -f '{{eget-packages}}' ]; then
  echo 'Package list not found: {{eget-packages}}'
  exit 1
fi

while read -ru 3 repo; do
  [[ -z "$repo" || "$repo" =~ ^# ]] && continue
  echo eget "$repo"
  # shellcheck disable=SC2086
  eget $repo
done 3< '{{eget-packages}}'
