AddPackage --foreign aconfmgr-git
AddPackage --foreign dms-shell-bin
AddPackage --foreign dotter-rs-bin
AddPackage --foreign dsearch-bin
AddPackage --foreign fcitx5-mcbopomofo-git
AddPackage --foreign google-chrome
AddPackage --foreign greetd-dms-greeter-git
AddPackage --foreign somo
AddPackage --foreign typora
AddPackage accountsservice
AddPackage alsa-firmware
AddPackage alsa-plugins
AddPackage alsa-utils
AddPackage amd-ucode
AddPackage base
AddPackage base-devel
AddPackage bat
AddPackage bluez
AddPackage bluez-hid2hci
AddPackage bluez-libs
AddPackage bluez-utils
AddPackage btrfs-assistant
AddPackage btrfs-progs
AddPackage cachyos-hooks
AddPackage cachyos-kernel-manager
AddPackage cachyos-keyring
AddPackage cachyos-micro-settings
AddPackage cachyos-mirrorlist
AddPackage cachyos-plymouth-bootanimation
AddPackage cachyos-rate-mirrors
AddPackage cachyos-settings
AddPackage cachyos-snapper-support
AddPackage cachyos-v3-mirrorlist
AddPackage cachyos-v4-mirrorlist
AddPackage calf
AddPackage celluloid
AddPackage chwd
AddPackage cmake
AddPackage cmatrix
AddPackage code
AddPackage cryptsetup
AddPackage device-mapper
AddPackage dgop
AddPackage discord
AddPackage dmidecode
AddPackage dnsmasq
AddPackage docker
AddPackage dosfstools
AddPackage duf
AddPackage dust
AddPackage e2fsprogs
AddPackage easyeffects
AddPackage efibootmgr
AddPackage efitools
AddPackage egl-wayland
AddPackage exfatprogs
AddPackage eza
AddPackage fastfetch
AddPackage fcitx5
AddPackage fcitx5-chinese-addons
AddPackage fcitx5-configtool
AddPackage fcitx5-gtk
AddPackage fcitx5-qt
AddPackage fd
AddPackage ffmpegthumbnailer
AddPackage fish
AddPackage fish-autopair
AddPackage fish-pure-prompt
AddPackage fisher
AddPackage fzf
AddPackage ghostty
AddPackage git
AddPackage git-delta
AddPackage git-lfs
AddPackage github-cli
AddPackage gst-libav
AddPackage gst-plugin-pipewire
AddPackage gst-plugin-va
AddPackage gst-plugins-bad
AddPackage i2c-tools
AddPackage inter-font
AddPackage iptables-nft
AddPackage iwd
AddPackage jq
AddPackage just
AddPackage keyd
AddPackage less
AddPackage lib32-mesa
AddPackage lib32-nvidia-utils
AddPackage lib32-opencl-nvidia
AddPackage lib32-vulkan-radeon
AddPackage libdvdcss
AddPackage libgsf
AddPackage libopenraw
AddPackage libva-nvidia-driver
AddPackage limine
AddPackage limine-mkinitcpio-hook
AddPackage limine-snapper-sync
AddPackage linux-cachyos
AddPackage linux-cachyos-headers
AddPackage linux-cachyos-lts
AddPackage linux-cachyos-lts-headers
AddPackage linux-cachyos-lts-nvidia-open
AddPackage linux-cachyos-nvidia-open
AddPackage linux-firmware
AddPackage localsend
AddPackage loupe
AddPackage lsb-release
AddPackage lsp-plugins-lv2
AddPackage lvm2
AddPackage mako
AddPackage man-db
AddPackage man-pages
AddPackage matugen
AddPackage meld
AddPackage mesa-utils
AddPackage micro
AddPackage mission-center
AddPackage mkinitcpio
AddPackage modemmanager
AddPackage nemo
AddPackage networkmanager
AddPackage networkmanager-openvpn
AddPackage ninja
AddPackage niri
AddPackage noto-color-emoji-fontconfig
AddPackage noto-fonts
AddPackage noto-fonts-cjk
AddPackage noto-fonts-emoji
AddPackage nss-mdns
AddPackage nvidia-prime
AddPackage nvidia-settings
AddPackage nvidia-utils
AddPackage opencl-nvidia
AddPackage openssh
AddPackage otf-font-awesome
AddPackage otf-geist-mono-nerd
AddPackage otf-monaspace
AddPackage otf-monaspace-nerdfonts
AddPackage pacman-contrib
AddPackage paru
AddPackage pipewire-alsa
AddPackage pipewire-pulse
AddPackage pkgfile
AddPackage plocate
AddPackage plymouth
AddPackage poppler-glib
AddPackage power-profiles-daemon
AddPackage python
AddPackage python-packaging
AddPackage qt5ct
AddPackage quickshell
AddPackage rebuild-detector
AddPackage ripgrep
AddPackage rsync
AddPackage rtkit
AddPackage rustup
AddPackage s-nail
AddPackage sbctl
AddPackage sd
AddPackage shellcheck
AddPackage shfmt
AddPackage smartmontools
AddPackage snapper
AddPackage sof-firmware
AddPackage sound-theme-freedesktop
AddPackage stow
AddPackage sunshine
AddPackage switcheroo-control
AddPackage sysfsutils
AddPackage tealdeer
AddPackage texinfo
AddPackage ttf-bitstream-vera
AddPackage ttf-dejavu
AddPackage ttf-fira-sans
AddPackage ttf-liberation
AddPackage ttf-opensans
AddPackage ufw
AddPackage unzip
AddPackage upower
AddPackage usb_modeswitch
AddPackage usbutils
AddPackage uv
AddPackage vim
AddPackage vulkan-radeon
AddPackage waybar
AddPackage wayland-protocols
AddPackage wget
AddPackage wireless-regdb
AddPackage wireplumber
AddPackage wl-clipboard
AddPackage wlogout
AddPackage woff2-font-awesome
AddPackage wofi
AddPackage wpa_supplicant
AddPackage xdg-user-dirs
AddPackage xf86-input-libinput
AddPackage xfsprogs
AddPackage xorg-server
AddPackage xorg-xdpyinfo
AddPackage xorg-xrandr
AddPackage xorg-xwayland
AddPackage xwayland-satellite
AddPackage zed
AddPackage zellij
