# shellcheck shell=bash
alias wget='wget -c --no-hsts'
export PATH=~/.local/bin:"$PATH"

[[ $- != *i* ]] && return # interactive section
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias la='eza -a --group-directories-first'
alias ll='eza -al --group-directories-first'
alias lt='eza -aTL 3 --group-directories-first'
alias tldr='tealdeer'

mkdir -p ~/.cache/bolt
function bolt-cache {
  local bin=$1
  local binf
  local cfile
  local cmd=$2
  binf=$(command -v "$bin")
  cfile="${3:-"$HOME/.cache/bolt/$bin"}"

  if [ ! -f "$cfile" ] || [ "$binf" -nt "$cfile" ]; then
    eval "$cmd" > "$cfile"
  fi
  _ret_val=$cfile
}

mkdir -p ~/.local/share/bash-completion/completions
function bolt-complete {
  if command -v "$1" >/dev/null; then
    bolt-cache "$@" "$HOME/.local/share/bash-completion/completions/$1"
  fi
}

function bolt-eval {
  bolt-cache "$@"
  # shellcheck disable=SC1090
  source "$_ret_val"
}

function hh {
  "$@" --help | bat -pl help
}

while read -r line; do
  [[ -z "$line" || "$line" =~ ^# ]] && continue
  bolt-complete "${line%% *}" "$line"
done < ~/dotfiles/sc/eget.pkg.completions

export FZF_DEFAULT_OPTS='--layout=reverse'
bolt-eval 'fzf'      'fzf --bash'
bolt-eval 'starship' 'starship init bash'
bolt-eval 'zoxide'   'zoxide init bash'
unset _ret_val
